### ISSUE TITLE
create documentation how-tos (in readme?)

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKnet-Website#16]
Write a README to explain how to

- [x] start website locally #88 
- [x] change text content in the home page
- [x] add or modify a hub #89 
- [x] change/upload images #90

Other content

- [x] screenshot of the page
- [x] license
- [x] partner and funder logos

**Comment by timmwille** [comment]
Linked to #6

**Comment by timmwille** [comment]
Does this all have to be there with https://github.com/ASKnetCommunity/ASKnet.Community/milestone/1

**Comment by MartinSchott** [comment]
take partner logos from: https://github.com/ASKnetCommunity/Training#partners-and-funder
but without nanologika

**Comment by MartinSchott** [comment]
here is the pad that we used for brainstorming and planning: https://doc.asknet.community/Sw71JqAvTJuNM95tOUTDVw?both#

@timmwille
